### PR TITLE
Inputs for Phase-2 templates with 25x100um size

### PR DESCRIPTION
**Pull request by tvami**
These files are needed to create Phase-2 templates with 25x100um size. These include 2D templates too, which enables new features for Phase-2 (simulating aging).

### CODE REVIEW

**Comment by tvami** [comment]
Hi @mrodozov ,
It seems the PR https://github.com/cms-sw/cmssw/pull/31796 doesn't automatically pick up the input files that are provided in this PR. Could you please merge this, so the tests for the other PR can succeed? Thanks!

**Comment by mrodozov** [comment]
Hi @tvami the cms-sw/cmssw#31796 definitely checks out  this PR:

```

18:12:19 Merge made by the 'recursive' strategy.
18:12:19  .../generror_summary_zp2293.out                    |  1444 +
18:12:19  .../generror_summary_zp2295.out                    |   534 +
18:12:19  .../phase2_T15_mapping.csv                         |    24 +
18:12:19  .../template_summary2D_zp2293.out                  | 72514 +++++++++++++++++++
18:12:19  .../template_summary2D_zp2295.out                  | 26754 +++++++
18:12:19  .../template_summary_zp2293.out                    | 12980 ++++
18:12:19  .../template_summary_zp2295.out                    |  4790 ++
18:12:19  7 files changed, 119040 insertions(+)
18:12:19  create mode 100644 Phase2_25by100_templates_2020October/generror_summary_zp2293.out
18:12:19  create mode 100644 Phase2_25by100_templates_2020October/generror_summary_zp2295.out
18:12:19  create mode 100644 Phase2_25by100_templates_2020October/phase2_T15_mapping.csv
18:12:19  create mode 100644 Phase2_25by100_templates_2020October/template_summary2D_zp2293.out
18:12:19  create mode 100644 Phase2_25by100_templates_2020October/template_summary2D_zp2295.out
18:12:19  create mode 100644 Phase2_25by100_templates_2020October/template_summary_zp2293.out
18:12:19  create mode 100644 Phase2_25by100_templates_2020October/template_summary_zp2295.out
```
this is from the console log : https://cmssdt.cern.ch/jenkins/job/ib-run-pr-tests/10092/console

**Comment by tvami** [comment]
Hi @mrodozov , in the unit test here
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8c7173/10092/unitTests.log
in the very bottom of the log, there is this msg:
"IOError: (2, 'No such file or directory', '/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-19-1100/src/CondTools/SiPixel/test/../data/Phase2_25by100_templates_2020October/phase2_T15_mapping.csv')"

In the console log that you just copied there is a line like
"18:12:19  create mode 100644 Phase2_25by100_templates_2020October/phase2_T15_mapping.csv"
So I don't understand why it doesn't find that file.

**Comment by tvami** [comment]
Hi @mrodozov I did this commit to see if that helps
https://github.com/cms-sw/cmssw/pull/31796/commits/d0d71bf50d94278e6be3cabc50d671a7678d3764
but apparently the tests are failing again too. Please note that everything works fine locally.

**Comment by mrodozov** [comment]
@tvami , @mmusich it's working now. Should I merge it ?

**Comment by mmusich** [comment]
@mrodozov yes please, thanks.

**Comment by christopheralanwest** [comment]
+1

**Pull request merged**
