### PR TITLE
add template / gen error files for IT version 7.1.1

### PR DESCRIPTION
**Pull request by mmusich**
Upload the necessary files for https://github.com/cms-sw/cmssw/pull/45775.
See for a description of the issue https://github.com/cms-sw/cmssw/pull/45775#issue-2480162067.

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * pull_request = https://github.com/cms-sw/cmssw/pull/45775

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
+alca
- Needed by #45775, but it can even be merged before it, as it only adds new files in cms-data
- Not for this PR: are there obsolete configurations in cms-data/CalibTracker-SiPixelESProducers that could be safely cleaned up from cms-data at some point?

**Comment by mmusich** [comment]
> Not for this PR: are there obsolete configurations in cms-data/CalibTracker-SiPixelESProducers that could be safely cleaned up from cms-data at some point?

I think technically we could remove all the configuration that are not exercised in tests. I let the TRK DPG to decide how and when organize the clean-up.

**Comment by mmusich** [comment]
@cmsbuild ignore tests-rejected with ib-failure

**Comment by mmusich** [comment]
urgent
   * to fix IB failures

**Comment by mmusich** [comment]
@smuzaffar @mandrenguyen please take a look.

**Comment by antoniovilela** [comment]
+1

**Comment by antoniovilela** [comment]
merge

**Pull request merged**
